version: "3.8"

services:
  db:
    container_name: db
    hostname: db.hyetheater.com
    restart: always
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root_password1
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/db.cnf:/etc/mysql/my.cnf
  
  api:
    container_name: api
    hostname: api.hyetheater.com
    restart: always
    command: /app/local_run.sh
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOSTNAME: db.hyetheater.com
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1
    volumes:
      - ./backend:/app
    depends_on:
      - "db"
  
  ui:
    container_name: ui
    hostname: app.hyetheater.com
    restart: always
    command: ./local_run.sh
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
    volumes:
      - './ui:/app'
      - '~/.npm:/root/.npm'
    depends_on:
      - "api"
   
volumes:
  mysql-data: {}

